services:
  db:
    image: postgres:alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dartPrecursor
      volumes: "data:/data"
      restart: always